'use strict';

/**
 * Catalogue des permissions et matrice rôles → permissions.
 * `reservee_division` : ne peut jamais être attribuée au Bureau Secrétariat de Direction ni à son Chef.
 * `delegable` : opération désignable, accordée temporairement par un acte de désignation.
 */
const PERMISSIONS = [
  // Système et sécurité (Admin Système — aucune autorité administrative)
  ['systeme.consulter', 'systeme', 'Consulter l’état technique du système'],
  ['systeme.configurer', 'systeme', 'Configurer les paramètres techniques du système'],
  ['systeme.maintenir', 'systeme', 'Opérations de maintenance (réinitialisation, maintenance)'],
  ['securite.superviser', 'securite', 'Superviser la sécurité (alertes, échecs de connexion, adresses IP, vérification)'],
  ['notification_systeme.envoyer', 'systeme', 'Envoyer une notification système'],
  ['sauvegarde.creer', 'sauvegarde', 'Lancer et consulter les sauvegardes'],
  ['sauvegarde.restaurer', 'sauvegarde', 'Restaurer une sauvegarde autorisée'],
  ['audit.consulter', 'audit', 'Consulter le journal d’audit'],
  ['audit.exporter', 'audit', 'Exporter le journal d’audit'],
  ['role.consulter', 'role', 'Consulter les rôles'],
  ['role.attribuer', 'role', 'Associer un rôle autorisé et paramétrer les rôles'],
  ['permission.consulter', 'role', 'Consulter les permissions'],
  ['organisation.configurer', 'organisation', 'Configurer techniquement l’organisation (sur décision du Directeur)'],
  ['referentiel.gerer', 'organisation', 'Gérer les référentiels techniques'],
  ['modele_carte.configurer', 'carte', 'Configurer le modèle graphique des cartes de service'],
  // Comptes et sessions
  ['compte.consulter', 'compte', 'Consulter les comptes utilisateurs'],
  ['compte.creer_initial', 'compte', 'Créer les comptes initiaux (Secrétaire Général, Directeur)'],
  ['compte.enroler', 'compte', 'Enrôler les agents de la liste déclarative validée'],
  ['compte.activer', 'compte', 'Activer un compte'],
  ['compte.desactiver', 'compte', 'Désactiver ou bloquer temporairement un compte'],
  ['compte.deverrouiller', 'compte', 'Débloquer un compte'],
  ['compte.reinitialiser_mot_de_passe', 'compte', 'Réinitialiser un mot de passe ou imposer son changement'],
  ['session.consulter', 'session', 'Consulter les sessions actives'],
  ['session.revoquer', 'session', 'Révoquer les sessions et refresh tokens'],
  // Liste déclarative des agents
  ['liste.consulter', 'personnel', 'Consulter la liste déclarative des agents de la Direction'],
  ['liste.gerer', 'personnel', 'Constituer la liste déclarative (import, inscription, retrait)'],
  ['liste.valider', 'personnel', 'Valider la liste déclarative des agents de la Direction'],
  // Organisation et personnel
  ['organisation.consulter', 'organisation', 'Consulter l’organigramme et le cadre organique'],
  ['organisation.gerer', 'organisation', 'Gérer les structures de la DEP'],
  ['cadre.gerer', 'organisation', 'Gérer les missions, attributions et postes organiques'],
  ['personnel.consulter', 'personnel', 'Consulter les fiches du personnel du périmètre'],
  ['personnel.gerer', 'personnel', 'Créer et modifier les fiches du personnel'],
  ['personnel.suivre', 'personnel', 'Assurer le suivi administratif du personnel', { delegable: true }],
  ['affectations.gerer', 'personnel', 'Gérer les affectations'],
  ['designations.gerer', 'personnel', 'Accorder et révoquer les désignations temporaires (sur acte)'],
  // Présences
  ['presences.consulter', 'presences', 'Consulter les présences du périmètre'],
  ['presences.saisir', 'presences', 'Créer et saisir les listes de présence du Bureau'],
  ['presences.preparer_direction', 'presences', 'Préparer les listes de présence de la Direction', { delegable: true }],
  ['presences.verifier', 'presences', 'Vérifier les listes de présence'],
  ['presences.soumettre', 'presences', 'Soumettre les listes de présence au Directeur'],
  ['presences.verrouiller', 'presences', 'Réceptionner et verrouiller les listes de présence'],
  // Courriers
  ['courriers.consulter', 'courriers', 'Consulter les courriers du périmètre'],
  ['courriers.enregistrer', 'courriers', 'Enregistrer les courriers entrants et sortants', { delegable: true }],
  ['courriers.transmettre', 'courriers', 'Transmettre un courrier dans la chaîne hiérarchique'],
  ['courriers.annoter', 'courriers', 'Annoter un courrier'],
  ['courriers.classer', 'courriers', 'Classer et archiver les courriers'],
  ['dossiers.transmettre', 'courriers', 'Transmettre les dossiers au Directeur', { delegable: true }],
  // Instructions et tâches
  ['instructions.consulter', 'instructions', 'Consulter les instructions du périmètre'],
  ['instructions.emettre', 'instructions', 'Adresser une instruction au subordonné direct'],
  ['instructions.executer', 'instructions', 'Exécuter une instruction reçue et en rendre compte'],
  ['instructions.valider', 'instructions', 'Valider ou retourner l’exécution d’une instruction émise'],
  ['taches.consulter', 'taches', 'Consulter les tâches du périmètre'],
  ['taches.attribuer', 'taches', 'Attribuer et valider les tâches des Agents du Bureau'],
  ['taches.executer', 'taches', 'Exécuter ses tâches et mettre à jour l’avancement'],
  // Documents
  ['documents.consulter', 'documents', 'Consulter les documents du périmètre'],
  ['documents.rediger', 'documents', 'Rédiger des projets de documents'],
  ['documents.examiner', 'documents', 'Examiner, retourner et transmettre les documents'],
  ['documents.viser', 'documents', 'Viser les documents avant validation par le Directeur'],
  ['documents.publier', 'documents', 'Publier les documents validés et choisir leur diffusion'],
  ['instructions.exceptionnelle', 'instructions', 'Adresser une instruction exceptionnelle à tout agent (copie au supérieur immédiat)'],
  ['demandes_info.emettre', 'demandes_info', 'Adresser une demande d’information au Directeur'],
  ['demandes_info.repondre', 'demandes_info', 'Répondre aux demandes d’information du Secrétaire Général'],
  ['reunions.organiser', 'reunions', 'Organiser les réunions de sa structure (ordre du jour, convocation, compte rendu)'],
  ['decisions.prendre', 'decisions', 'Prendre et enregistrer les décisions du Directeur, les abandonner'],
  ['agenda.consulter', 'agenda', 'Consulter l’agenda du Directeur'],
  ['agenda.gerer', 'agenda', 'Tenir l’agenda du Directeur (audiences, réunions, rappels)'],
  ['documents.valider_final', 'documents', 'Valider définitivement et signer les documents'],
  ['documents.archiver', 'documents', 'Archiver les documents'],
  // PIP
  ['pip.consulter', 'pip', 'Consulter les fiches PIP'],
  ['pip.rediger', 'pip', 'Rédiger une fiche PIP'],
  ['pip.verifier', 'pip', 'Vérifier une fiche PIP'],
  ['pip.valider', 'pip', 'Valider une fiche PIP'],
  ['pip.archiver', 'pip', 'Archiver une fiche PIP'],
  // Rapports
  ['rapports.consulter', 'rapports', 'Consulter les rapports et statistiques du périmètre'],
  ['rapport_securite.consulter', 'rapports', 'Consulter les rapports mensuels de sécurité'],
  ['actes.consulter', 'gouvernance', 'Consulter le registre des actes administratifs'],
  ['actes.preparer', 'gouvernance', 'Préparer l’enregistrement des actes administratifs'],
  ['actes.valider', 'gouvernance', 'Valider les actes administratifs relevant du Directeur'],
  ['actes.valider_direction', 'gouvernance', 'Valider les actes relatifs au poste de Directeur'],
  ['actes.enregistrer_direction', 'gouvernance', 'Enregistrer les actes relatifs au poste de Directeur'],
  ['operations.confirmer', 'gouvernance', 'Confirmer ou refuser les opérations critiques de l’Admin Système'],
  ['acces_support.demander', 'gouvernance', 'Demander un accès de support temporaire'],
  ['acces_support.valider', 'gouvernance', 'Valider, refuser ou révoquer un accès de support'],
  ['urgence.activer', 'gouvernance', 'Activer le compte d’urgence'],
  ['urgence.desactiver', 'gouvernance', 'Refermer le compte d’urgence'],
  ['cartes.consulter', 'cartes', 'Consulter le registre des cartes de service'],
  ['cartes.preparer', 'cartes', 'Préparer, imprimer et remettre les cartes de service'],
  ['cartes.valider', 'cartes', 'Valider, suspendre ou annuler les cartes de service'],
  ['sauvegarde.valider_restauration', 'gouvernance', 'Valider ou refuser une demande de restauration de la base'],
  ['exports.generer', 'rapports', 'Générer des exports PDF / Excel / Word'],
  ['supervision.globale', 'supervision', 'Supervision globale en lecture de la DEP'],
  // Réservées aux Divisions
  ['division.gerer', 'division', 'Gérer une Division', { reservee_division: true }],
  ['division.superviser', 'division', 'Superviser une Division et ses Bureaux', { reservee_division: true }],
  ['division.valider', 'division', 'Valider au niveau de la Division', { reservee_division: true }],
  ['chef_division.agir', 'division', 'Agir en qualité de Chef de Division', { reservee_division: true }],
];

const ROLES = [
  { code: 'ADMIN_SYSTEME', libelle: 'Admin Système', perimetre_defaut: 'SYSTEME', description: 'Fonctionnement technique, sécurité et disponibilité de SIG-DEP. Aucune autorité administrative : ne remplace jamais le Directeur, un Chef de Division ou un Chef de Bureau.' },
  { code: 'SECRETAIRE_GENERAL', libelle: 'Secrétaire Général', perimetre_defaut: 'SUPERVISION_GLOBALE', description: 'Supervision globale et consultation. Adresse ses instructions exclusivement au Directeur.' },
  { code: 'DIRECTEUR', libelle: 'Directeur', perimetre_defaut: 'DIRECTION', description: 'Responsable administratif et opérationnel de la Direction d’Études et Planification.' },
  { code: 'CHEF_DIVISION', libelle: 'Chef de Division', perimetre_defaut: 'DIVISION', description: 'Autorité limitée à sa Division et aux Bureaux qui lui sont rattachés.' },
  { code: 'CHEF_BUREAU', libelle: 'Chef de Bureau', perimetre_defaut: 'BUREAU', description: 'Autorité limitée à son Bureau et à ses Agents.' },
  { code: 'AGENT', libelle: 'Agent', perimetre_defaut: 'PERSONNEL', description: 'Accès à ses activités et aux informations autorisées de son Bureau.' },
];

const MATRICE = {
  ADMIN_SYSTEME: [
    'systeme.consulter', 'systeme.configurer', 'systeme.maintenir', 'securite.superviser', 'notification_systeme.envoyer',
    'sauvegarde.creer', 'sauvegarde.restaurer', 'audit.consulter', 'audit.exporter',
    'role.consulter', 'role.attribuer', 'permission.consulter', 'organisation.consulter', 'organisation.configurer', 'referentiel.gerer',
    'modele_carte.configurer',
    'compte.consulter', 'compte.creer_initial', 'compte.enroler', 'compte.activer', 'compte.desactiver', 'compte.deverrouiller',
    'compte.reinitialiser_mot_de_passe', 'session.consulter', 'session.revoquer', 'rapport_securite.consulter',
    'actes.enregistrer_direction', 'acces_support.demander', 'urgence.desactiver',
  ],
  SECRETAIRE_GENERAL: [
    'supervision.globale', 'organisation.consulter', 'personnel.consulter', 'presences.consulter',
    'courriers.consulter', 'instructions.consulter', 'instructions.emettre', 'instructions.valider',
    'taches.consulter', 'documents.consulter', 'pip.consulter', 'rapports.consulter', 'exports.generer',
    'actes.consulter', 'actes.valider_direction', 'urgence.activer', 'urgence.desactiver',
    'demandes_info.emettre',
  ],
  DIRECTEUR: [
    'organisation.consulter', 'organisation.gerer', 'cadre.gerer',
    'personnel.consulter', 'personnel.gerer', 'personnel.suivre', 'affectations.gerer', 'designations.gerer', 'actes.consulter', 'actes.preparer', 'actes.valider',
    'operations.confirmer', 'acces_support.valider', 'urgence.activer', 'urgence.desactiver',
    'cartes.consulter', 'cartes.preparer', 'cartes.valider',
    'compte.consulter', 'compte.activer', 'compte.desactiver', 'rapport_securite.consulter', 'sauvegarde.valider_restauration', 'liste.consulter', 'liste.gerer', 'liste.valider',
    'presences.consulter', 'presences.verrouiller',
    'courriers.consulter', 'courriers.enregistrer', 'courriers.transmettre', 'courriers.annoter', 'courriers.classer',
    'dossiers.transmettre',
    'instructions.consulter', 'instructions.emettre', 'instructions.executer', 'instructions.valider', 'instructions.exceptionnelle',
    'demandes_info.repondre', 'reunions.organiser', 'decisions.prendre', 'agenda.consulter', 'agenda.gerer',
    'taches.consulter',
    'documents.consulter', 'documents.rediger', 'documents.examiner', 'documents.valider_final', 'documents.publier', 'documents.archiver',
    'pip.consulter', 'pip.rediger', 'pip.verifier', 'pip.valider', 'pip.archiver',
    'rapports.consulter', 'exports.generer',
    'division.gerer', 'division.superviser', 'division.valider',
  ],
  CHEF_DIVISION: [
    'organisation.consulter', 'personnel.consulter',
    'presences.consulter', 'presences.verifier',
    'courriers.consulter', 'courriers.transmettre', 'courriers.annoter',
    'instructions.consulter', 'instructions.emettre', 'instructions.executer', 'instructions.valider',
    'taches.consulter',
    'documents.consulter', 'documents.rediger', 'documents.examiner', 'documents.viser', 'reunions.organiser',
    'pip.consulter', 'pip.rediger', 'pip.verifier',
    'rapports.consulter', 'exports.generer',
    'division.gerer', 'division.superviser', 'division.valider', 'chef_division.agir',
  ],
  CHEF_BUREAU: [
    'organisation.consulter', 'personnel.consulter',
    'presences.consulter', 'presences.saisir', 'presences.verifier', 'presences.soumettre',
    'courriers.consulter', 'courriers.transmettre', 'courriers.annoter',
    'instructions.consulter', 'instructions.executer',
    'taches.consulter', 'taches.attribuer',
    'documents.consulter', 'documents.rediger', 'documents.examiner', 'documents.viser', 'reunions.organiser',
    'pip.consulter', 'pip.rediger',
    'rapports.consulter', 'exports.generer',
  ],
  AGENT: [
    'organisation.consulter',
    'courriers.consulter',
    'instructions.consulter', 'instructions.executer',
    'taches.consulter', 'taches.executer',
    'documents.consulter', 'documents.rediger',
    'pip.consulter', 'pip.rediger',
    'exports.generer',
  ],
};

module.exports = { PERMISSIONS, ROLES, MATRICE };
